sonar.projectKey=intelligent-devsecops-pipeline
sonar.organization=jubit-pincy
sonar.sources=.
sonar.exclusions=**/risk-engine/**,**/reports/**,**/.github/**,**/node_modules/**,**/venv/**,**/App.Tests/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml