sonar.projectKey=intelligent-devsecops-pipeline
sonar.organization=jubit-pincy
sonar.sources=.
sonar.exclusions=\
  **/risk-engine/**,\
  **/reports/**,\
  **/.github/**,\
  **/node_modules/**,\
  **/venv/**,\
  **/bin/**,\
  **/obj/**,\
  **/*.dockerfile,\
  **/Dockerfile*,\
  **/Jenkinsfile*,\
  **/*.yml,\
  **/*.yaml,\
  **/*.md,\
  **/*.txt,\
  **/*.json,\
  **/*.xml,\
  **/*.html,\
  **/*.css,\
  **/*.sh
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml