sonar.projectKey=intelligent-devsecops-pipeline
sonar.working.directory=/home/jubit/DevSecOpsProject/App/.sonarqube/out/.sonar
sonar.projectBaseDir=/home/jubit/DevSecOpsProject/App
sonar.pullrequest.cache.basepath=/home/jubit/DevSecOpsProject/App

9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.projectKey=intelligent-devsecops-pipeline:9D7F5858-DA2A-4B56-9160-F56CF21C5A8E
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.projectName=App
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.projectBaseDir=/home/jubit/DevSecOpsProject/App
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.sourceEncoding=utf-8
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.tests=
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.sources=\
"/home/jubit/DevSecOpsProject/App/Controllers/WeatherController.cs",\
"/home/jubit/DevSecOpsProject/App/Controllers/WeatherForecastController.cs",\
"/home/jubit/DevSecOpsProject/App/Models/LoginRequest.cs",\
"/home/jubit/DevSecOpsProject/App/Program.cs",\
"/home/jubit/DevSecOpsProject/App/Services/IWeatherService.cs",\
"/home/jubit/DevSecOpsProject/App/Services/WeatherService.cs",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/App.GlobalUsings.g.cs",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/App.AssemblyInfo.cs",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/App.MvcApplicationPartsAssemblyInfo.cs",\
"/home/jubit/DevSecOpsProject/App/wwwroot/index.html",\
"/home/jubit/DevSecOpsProject/App/appsettings.Development.json",\
"/home/jubit/DevSecOpsProject/App/appsettings.json",\
"/home/jubit/DevSecOpsProject/App/App.http",\
"/home/jubit/DevSecOpsProject/App/Properties/launchSettings.json",\
"/home/jubit/DevSecOpsProject/App/obj/SecureApp.csproj.nuget.dgspec.json",\
"/home/jubit/DevSecOpsProject/App/obj/App.csproj.nuget.dgspec.json",\
"/home/jubit/DevSecOpsProject/App/obj/project.assets.json",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/staticwebassets.build.json",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/SecureApp.sourcelink.json",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/App.sourcelink.json",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/staticwebassets.development.json",\
"/home/jubit/DevSecOpsProject/App/obj/Debug/net8.0/staticwebassets.pack.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/SecureApp.staticwebassets.runtime.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/appsettings.Development.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/appsettings.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/App.deps.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/SecureApp.deps.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/App.staticwebassets.runtime.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/App.runtimeconfig.json",\
"/home/jubit/DevSecOpsProject/App/bin/Debug/net8.0/SecureApp.runtimeconfig.json"

9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.cs.analyzer.projectOutPaths=\
"/home/jubit/DevSecOpsProject/App/.sonarqube/out/0"
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.cs.roslyn.reportFilePaths=\
"/home/jubit/DevSecOpsProject/App/.sonarqube/out/0/Issues.json"
9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.cs.scanner.telemetry=\
"/home/jubit/DevSecOpsProject/App/.sonarqube/out/0/Telemetry.json"

9D7F5858-DA2A-4B56-9160-F56CF21C5A8E.sonar.working.directory=/home/jubit/DevSecOpsProject/App/.sonarqube/out/.sonar/mod0
sonar.organization=jubit-pincy
sonar.visualstudio.enable=false
sonar.host.url=https://sonarcloud.io

sonar.modules=9D7F5858-DA2A-4B56-9160-F56CF21C5A8E

